// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RejestrNieruchomosciNew;

namespace RejestrNieruchomosciNew.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20190621054317_r1")]
    partial class r1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RejestrNieruchomosciNew.Dzialka", b =>
                {
                    b.Property<int>("DzialkaId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Kwakt");

                    b.Property<string>("Kwzrob");

                    b.Property<string>("Numer");

                    b.Property<int>("ObrebId");

                    b.Property<decimal?>("Pow");

                    b.HasKey("DzialkaId");

                    b.ToTable("Dzialka");

                    b.HasData(
                        new
                        {
                            DzialkaId = 1,
                            Kwzrob = "5454",
                            Numer = "1",
                            ObrebId = 0,
                            Pow = 1200m
                        },
                        new
                        {
                            DzialkaId = 2,
                            Numer = "2",
                            ObrebId = 0,
                            Pow = 1500m
                        },
                        new
                        {
                            DzialkaId = 3,
                            Kwzrob = "5822",
                            Numer = "3",
                            ObrebId = 0,
                            Pow = 1000m
                        },
                        new
                        {
                            DzialkaId = 4,
                            Kwakt = "GD1G/13005/5",
                            Numer = "4",
                            ObrebId = 0,
                            Pow = 1000m
                        },
                        new
                        {
                            DzialkaId = 5,
                            Kwakt = "GD1G/13005/5",
                            Numer = "5",
                            ObrebId = 0,
                            Pow = 400m
                        },
                        new
                        {
                            DzialkaId = 6,
                            Kwakt = "GD1G/13005/5",
                            Numer = "6",
                            ObrebId = 0,
                            Pow = 400m
                        },
                        new
                        {
                            DzialkaId = 7,
                            Kwakt = "GD1G/13005/5",
                            Numer = "7",
                            ObrebId = 0,
                            Pow = 10m
                        },
                        new
                        {
                            DzialkaId = 8,
                            Kwakt = "GD1G/13005/5",
                            Numer = "8",
                            ObrebId = 0,
                            Pow = 10m
                        },
                        new
                        {
                            DzialkaId = 9,
                            Kwakt = "GD1G/13005/5",
                            Numer = "9",
                            ObrebId = 0,
                            Pow = 10m
                        },
                        new
                        {
                            DzialkaId = 10,
                            Kwakt = "GD1G/13005/5",
                            Numer = "10",
                            ObrebId = 0,
                            Pow = 10m
                        },
                        new
                        {
                            DzialkaId = 11,
                            Kwakt = "GD1G/13005/5",
                            Numer = "11",
                            ObrebId = 0,
                            Pow = 1052m
                        },
                        new
                        {
                            DzialkaId = 12,
                            Kwakt = "GD1G/15225/1",
                            Numer = "12",
                            ObrebId = 0,
                            Pow = 859m
                        },
                        new
                        {
                            DzialkaId = 13,
                            Kwakt = "GD1G/15225/1",
                            Numer = "13",
                            ObrebId = 0,
                            Pow = 859m
                        },
                        new
                        {
                            DzialkaId = 14,
                            Kwakt = "GD1G/15225/1",
                            Kwzrob = "GD1G/00045487/1",
                            Numer = "14",
                            ObrebId = 0,
                            Pow = 859m
                        },
                        new
                        {
                            DzialkaId = 15,
                            Kwakt = "GD1G/15225/1",
                            Kwzrob = "GD1G/00045487/1",
                            Numer = "15",
                            ObrebId = 0,
                            Pow = 859m
                        },
                        new
                        {
                            DzialkaId = 16,
                            Kwakt = "GD1G/15225/1",
                            Kwzrob = "GD1G/00045487/1",
                            Numer = "16",
                            ObrebId = 0,
                            Pow = 859m
                        },
                        new
                        {
                            DzialkaId = 17,
                            Kwakt = "GD1G/15/1",
                            Kwzrob = "GD1G/00045487/1",
                            Numer = "17",
                            ObrebId = 0,
                            Pow = 859m
                        },
                        new
                        {
                            DzialkaId = 18,
                            Kwakt = "GD1G/155/1",
                            Kwzrob = "GD1G/00045487/1",
                            Numer = "18",
                            ObrebId = 0,
                            Pow = 859m
                        },
                        new
                        {
                            DzialkaId = 19,
                            Kwakt = "GD1G/15345/1",
                            Kwzrob = "GD1G/00045487/1",
                            Numer = "19",
                            ObrebId = 0,
                            Pow = 859m
                        },
                        new
                        {
                            DzialkaId = 20,
                            Kwakt = "GD1G/152325/1",
                            Kwzrob = "GD1G/00045487/1",
                            Numer = "20",
                            ObrebId = 0,
                            Pow = 859m
                        },
                        new
                        {
                            DzialkaId = 21,
                            Kwakt = "GD1G/34234/1",
                            Kwzrob = "GD1G/00045487/1",
                            Numer = "21",
                            ObrebId = 0,
                            Pow = 120m
                        },
                        new
                        {
                            DzialkaId = 22,
                            Kwakt = "GD1G/1855/1",
                            Kwzrob = "GD1G/00045487/1",
                            Numer = "22",
                            ObrebId = 0,
                            Pow = 120m
                        },
                        new
                        {
                            DzialkaId = 23,
                            Kwakt = "GD1G/1855/1",
                            Kwzrob = "GD1G/00045487/1",
                            Numer = "23",
                            ObrebId = 0,
                            Pow = 120m
                        },
                        new
                        {
                            DzialkaId = 24,
                            Kwakt = "GD1G/9955/1",
                            Kwzrob = "GD1G/00045487/1",
                            Numer = "24",
                            ObrebId = 0,
                            Pow = 120m
                        },
                        new
                        {
                            DzialkaId = 25,
                            Kwakt = "GD1G/9955/1",
                            Kwzrob = "GD1G/00045487/1",
                            Numer = "25",
                            ObrebId = 0,
                            Pow = 120m
                        },
                        new
                        {
                            DzialkaId = 26,
                            Kwakt = "GD1G/9955/1",
                            Kwzrob = "GD1G/00045487/1",
                            Numer = "25",
                            ObrebId = 0,
                            Pow = 120m
                        },
                        new
                        {
                            DzialkaId = 27,
                            Kwakt = "GD1G/9955/1",
                            Kwzrob = "GD1G/100087/2",
                            Numer = "27",
                            ObrebId = 0,
                            Pow = 120m
                        },
                        new
                        {
                            DzialkaId = 28,
                            Kwakt = "GD1G/9955/1",
                            Kwzrob = "GD1G/100087/2",
                            Numer = "28",
                            ObrebId = 0,
                            Pow = 120m
                        },
                        new
                        {
                            DzialkaId = 29,
                            Kwakt = "GD1G/9955/1",
                            Kwzrob = "GD1G/100087/2",
                            Numer = "29",
                            ObrebId = 0,
                            Pow = 120m
                        },
                        new
                        {
                            DzialkaId = 30,
                            Kwakt = "GD1G/9955/6",
                            Kwzrob = "GD1G/100087/2",
                            Numer = "30",
                            ObrebId = 0,
                            Pow = 120m
                        },
                        new
                        {
                            DzialkaId = 31,
                            Kwakt = "GD1G/9955/6",
                            Kwzrob = "GD1G/100087/2",
                            Numer = "31",
                            ObrebId = 0,
                            Pow = 149m
                        },
                        new
                        {
                            DzialkaId = 32,
                            Kwakt = "GD1G/9955/6",
                            Kwzrob = "GD1G/100087/2",
                            Numer = "32",
                            ObrebId = 0,
                            Pow = 149m
                        },
                        new
                        {
                            DzialkaId = 33,
                            Kwakt = "GD1G/9955/6",
                            Kwzrob = "GD1G/100087/2",
                            Numer = "33",
                            ObrebId = 0,
                            Pow = 149m
                        },
                        new
                        {
                            DzialkaId = 34,
                            Kwakt = "GD1G/9955/6",
                            Kwzrob = "GD1G/100087/2",
                            Numer = "34",
                            ObrebId = 0,
                            Pow = 149m
                        },
                        new
                        {
                            DzialkaId = 35,
                            Kwakt = "GD1G/9955/6",
                            Kwzrob = "GD1G/100087/2",
                            Numer = "35",
                            ObrebId = 0,
                            Pow = 149m
                        },
                        new
                        {
                            DzialkaId = 36,
                            Kwakt = "GD1G/9955/6",
                            Kwzrob = "GD1G/100087/2",
                            Numer = "36",
                            ObrebId = 0,
                            Pow = 149m
                        },
                        new
                        {
                            DzialkaId = 37,
                            Kwakt = "GD1G/9955/6",
                            Kwzrob = "GD1G/100087/2",
                            Numer = "37",
                            ObrebId = 0,
                            Pow = 149m
                        },
                        new
                        {
                            DzialkaId = 38,
                            Kwakt = "GD1G/955/6",
                            Kwzrob = "GD1G/900087/3",
                            Numer = "38",
                            ObrebId = 0,
                            Pow = 149m
                        },
                        new
                        {
                            DzialkaId = 39,
                            Kwakt = "GD1G/955/6",
                            Kwzrob = "GD1G/900087/3",
                            Numer = "39",
                            ObrebId = 0,
                            Pow = 149m
                        },
                        new
                        {
                            DzialkaId = 40,
                            Kwakt = "GD1G/955/6",
                            Kwzrob = "GD1G/900087/3",
                            Numer = "40",
                            ObrebId = 0,
                            Pow = 149m
                        },
                        new
                        {
                            DzialkaId = 41,
                            Kwakt = "GD1G/955/6",
                            Kwzrob = "GD1G/900087/3",
                            Numer = "41",
                            ObrebId = 0,
                            Pow = 249m
                        },
                        new
                        {
                            DzialkaId = 42,
                            Kwakt = "GD1G/955/6",
                            Kwzrob = "GD1G/900087/3",
                            Numer = "42",
                            ObrebId = 0,
                            Pow = 249m
                        },
                        new
                        {
                            DzialkaId = 43,
                            Kwakt = "GD1G/955/6",
                            Kwzrob = "GD1G/900087/3",
                            Numer = "43",
                            ObrebId = 0,
                            Pow = 249m
                        },
                        new
                        {
                            DzialkaId = 44,
                            Kwakt = "GD1G/955/6",
                            Kwzrob = "GD1G/900087/3",
                            Numer = "44",
                            ObrebId = 0,
                            Pow = 249m
                        },
                        new
                        {
                            DzialkaId = 45,
                            Kwakt = "GD1G/955/13",
                            Kwzrob = "GD1G/900087/3",
                            Numer = "45",
                            ObrebId = 0,
                            Pow = 249m
                        },
                        new
                        {
                            DzialkaId = 46,
                            Kwakt = "GD1G/955/13",
                            Kwzrob = "GD1G/900087/3",
                            Numer = "46",
                            ObrebId = 0,
                            Pow = 249m
                        },
                        new
                        {
                            DzialkaId = 47,
                            Kwakt = "GD1G/955/13",
                            Kwzrob = "GD1G/900087/3",
                            Numer = "47",
                            ObrebId = 0,
                            Pow = 249m
                        },
                        new
                        {
                            DzialkaId = 48,
                            Kwakt = "GD1G/955/13",
                            Kwzrob = "GD1G/900087/3",
                            Numer = "48",
                            ObrebId = 0,
                            Pow = 249m
                        },
                        new
                        {
                            DzialkaId = 49,
                            Kwakt = "GD1G/955/13",
                            Kwzrob = "GD1G/900087/3",
                            Numer = "49",
                            ObrebId = 0,
                            Pow = 13m
                        },
                        new
                        {
                            DzialkaId = 50,
                            Kwakt = "GD1G/955/13",
                            Kwzrob = "GD1G/908342/5",
                            Numer = "50",
                            ObrebId = 0,
                            Pow = 13m
                        },
                        new
                        {
                            DzialkaId = 51,
                            Kwakt = "GD1G/13005/5",
                            Kwzrob = "GD1G/908342/5",
                            Numer = "51",
                            ObrebId = 0,
                            Pow = 13m
                        },
                        new
                        {
                            DzialkaId = 52,
                            Kwakt = "GD1G/13005/5",
                            Kwzrob = "GD1G/908342/5",
                            Numer = "52",
                            ObrebId = 0,
                            Pow = 13m
                        },
                        new
                        {
                            DzialkaId = 53,
                            Kwakt = "GD1G/13005/5",
                            Kwzrob = "GD1G/908342/5",
                            Numer = "53",
                            ObrebId = 0,
                            Pow = 13m
                        },
                        new
                        {
                            DzialkaId = 54,
                            Kwakt = "GD1G/113005/1",
                            Kwzrob = "GD1G/908342/5",
                            Numer = "54",
                            ObrebId = 0,
                            Pow = 13m
                        },
                        new
                        {
                            DzialkaId = 55,
                            Kwakt = "GD1G/113005/1",
                            Kwzrob = "GD1G/908342/5",
                            Numer = "55",
                            ObrebId = 0,
                            Pow = 13m
                        },
                        new
                        {
                            DzialkaId = 56,
                            Kwakt = "GD1G/113005/1",
                            Kwzrob = "GD1G/908342/5",
                            Numer = "56",
                            ObrebId = 0,
                            Pow = 89m
                        },
                        new
                        {
                            DzialkaId = 57,
                            Kwakt = "GD1G/113005/1",
                            Kwzrob = "GD1G/908342/5",
                            Numer = "57",
                            ObrebId = 0,
                            Pow = 89m
                        },
                        new
                        {
                            DzialkaId = 58,
                            Kwakt = "GD1G/113005/1",
                            Kwzrob = "GD1G/908342/5",
                            Numer = "58",
                            ObrebId = 0,
                            Pow = 89m
                        },
                        new
                        {
                            DzialkaId = 59,
                            Kwakt = "GD1G/0000955/13",
                            Kwzrob = "GD1G/908342/5",
                            Numer = "59",
                            ObrebId = 0,
                            Pow = 89m
                        },
                        new
                        {
                            DzialkaId = 60,
                            Kwakt = "GD1G/0000955/13",
                            Kwzrob = "GD1G/908342/5",
                            Numer = "60",
                            ObrebId = 0,
                            Pow = 89m
                        },
                        new
                        {
                            DzialkaId = 61,
                            Kwakt = "GD1G/0000955/13",
                            Kwzrob = "GD1G/908342/5",
                            Numer = "61",
                            ObrebId = 0,
                            Pow = 89m
                        },
                        new
                        {
                            DzialkaId = 62,
                            Kwakt = "GD1G/0000955/13",
                            Kwzrob = "GD1G/908342/5",
                            Numer = "62",
                            ObrebId = 0,
                            Pow = 89m
                        },
                        new
                        {
                            DzialkaId = 63,
                            Kwakt = "GD1G/0000955/13",
                            Kwzrob = "GD1G/908342/5",
                            Numer = "63",
                            ObrebId = 0,
                            Pow = 89m
                        },
                        new
                        {
                            DzialkaId = 64,
                            Kwakt = "GD1G/0000955/13",
                            Kwzrob = "GD1G/988842/13",
                            Numer = "64",
                            ObrebId = 0,
                            Pow = 89m
                        },
                        new
                        {
                            DzialkaId = 65,
                            Kwakt = "GD1G/0005/13",
                            Kwzrob = "GD1G/988842/13",
                            Numer = "65",
                            ObrebId = 0,
                            Pow = 89m
                        },
                        new
                        {
                            DzialkaId = 66,
                            Kwakt = "GD1G/0005/13",
                            Kwzrob = "GD1G/988842/13",
                            Numer = "66",
                            ObrebId = 0,
                            Pow = 18m
                        },
                        new
                        {
                            DzialkaId = 67,
                            Kwakt = "GD1G/0005/13",
                            Kwzrob = "GD1G/988842/13",
                            Numer = "67",
                            ObrebId = 0,
                            Pow = 18m
                        },
                        new
                        {
                            DzialkaId = 68,
                            Kwakt = "GD1G/0005/13",
                            Kwzrob = "GD1G/988842/13",
                            Numer = "68",
                            ObrebId = 0,
                            Pow = 18m
                        },
                        new
                        {
                            DzialkaId = 69,
                            Kwakt = "GD1G/0005/13",
                            Kwzrob = "GD1G/988842/13",
                            Numer = "69",
                            ObrebId = 0,
                            Pow = 18m
                        },
                        new
                        {
                            DzialkaId = 70,
                            Kwakt = "GD1G/0005/13",
                            Numer = "70",
                            ObrebId = 0
                        });
                });

            modelBuilder.Entity("RejestrNieruchomosciNew.GminaSlo", b =>
                {
                    b.Property<int>("GminaSloId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nazwa");

                    b.HasKey("GminaSloId");

                    b.ToTable("GminaSlo");

                    b.HasData(
                        new
                        {
                            GminaSloId = 1,
                            Nazwa = "miasto Gdańsk"
                        },
                        new
                        {
                            GminaSloId = 2,
                            Nazwa = "miasto Sopot"
                        },
                        new
                        {
                            GminaSloId = 3,
                            Nazwa = "miasto Pruszcz Gdański"
                        },
                        new
                        {
                            GminaSloId = 4,
                            Nazwa = "gmina Gdańsk"
                        },
                        new
                        {
                            GminaSloId = 5,
                            Nazwa = "gmina Pruszcz Gdański"
                        },
                        new
                        {
                            GminaSloId = 6,
                            Nazwa = "gmina Żukowo"
                        },
                        new
                        {
                            GminaSloId = 7,
                            Nazwa = "gmina Kolbudy"
                        });
                });

            modelBuilder.Entity("RejestrNieruchomosciNew.Obreb", b =>
                {
                    b.Property<int>("ObrebId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DzialkaId");

                    b.Property<int>("GminaSloId");

                    b.Property<string>("Nazwa");

                    b.HasKey("ObrebId");

                    b.HasIndex("DzialkaId");

                    b.HasIndex("GminaSloId");

                    b.ToTable("Obreb");

                    b.HasData(
                        new
                        {
                            ObrebId = 1,
                            GminaSloId = 1,
                            Nazwa = "010"
                        },
                        new
                        {
                            ObrebId = 2,
                            GminaSloId = 1,
                            Nazwa = "020"
                        },
                        new
                        {
                            ObrebId = 3,
                            GminaSloId = 1,
                            Nazwa = "030"
                        },
                        new
                        {
                            ObrebId = 4,
                            GminaSloId = 1,
                            Nazwa = "040"
                        },
                        new
                        {
                            ObrebId = 5,
                            GminaSloId = 1,
                            Nazwa = "050"
                        },
                        new
                        {
                            ObrebId = 6,
                            GminaSloId = 1,
                            Nazwa = "060"
                        },
                        new
                        {
                            ObrebId = 7,
                            GminaSloId = 1,
                            Nazwa = "070"
                        },
                        new
                        {
                            ObrebId = 8,
                            GminaSloId = 1,
                            Nazwa = "080"
                        },
                        new
                        {
                            ObrebId = 9,
                            GminaSloId = 1,
                            Nazwa = "090"
                        },
                        new
                        {
                            ObrebId = 10,
                            GminaSloId = 1,
                            Nazwa = "100"
                        },
                        new
                        {
                            ObrebId = 11,
                            GminaSloId = 1,
                            Nazwa = "110"
                        },
                        new
                        {
                            ObrebId = 12,
                            GminaSloId = 1,
                            Nazwa = "120"
                        },
                        new
                        {
                            ObrebId = 13,
                            GminaSloId = 1,
                            Nazwa = "130"
                        },
                        new
                        {
                            ObrebId = 14,
                            GminaSloId = 2,
                            Nazwa = "010"
                        },
                        new
                        {
                            ObrebId = 15,
                            GminaSloId = 2,
                            Nazwa = "020"
                        },
                        new
                        {
                            ObrebId = 16,
                            GminaSloId = 2,
                            Nazwa = "030"
                        },
                        new
                        {
                            ObrebId = 17,
                            GminaSloId = 2,
                            Nazwa = "040"
                        },
                        new
                        {
                            ObrebId = 18,
                            GminaSloId = 2,
                            Nazwa = "050"
                        },
                        new
                        {
                            ObrebId = 19,
                            GminaSloId = 2,
                            Nazwa = "060"
                        },
                        new
                        {
                            ObrebId = 20,
                            GminaSloId = 2,
                            Nazwa = "070"
                        },
                        new
                        {
                            ObrebId = 21,
                            GminaSloId = 3,
                            Nazwa = "010"
                        },
                        new
                        {
                            ObrebId = 22,
                            GminaSloId = 3,
                            Nazwa = "020"
                        },
                        new
                        {
                            ObrebId = 23,
                            GminaSloId = 4,
                            Nazwa = "030"
                        },
                        new
                        {
                            ObrebId = 24,
                            GminaSloId = 4,
                            Nazwa = "040"
                        },
                        new
                        {
                            ObrebId = 25,
                            GminaSloId = 4,
                            Nazwa = "050"
                        });
                });

            modelBuilder.Entity("RejestrNieruchomosciNew.Obreb", b =>
                {
                    b.HasOne("RejestrNieruchomosciNew.Dzialka", "Dzialka")
                        .WithMany("Obreb")
                        .HasForeignKey("DzialkaId");

                    b.HasOne("RejestrNieruchomosciNew.GminaSlo", "GminaSlo")
                        .WithMany("Obreb")
                        .HasForeignKey("GminaSloId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
